USE STOCZNIA7
SELECT * from  KLIENCI--
SELECT * from  PRYWATNI--
SELECT * from  FIRMY--
SELECT * from  ZAMOWIENIA--
SELECT * from  FABRYKI -----------------
SELECT * from  WYPOSAZENIE -------------
SELECT * from  MODELE_JACHTOW --
SELECT * from  EGZEMPLARZE_Z_WYPOSAZENIEM
SELECT * from  ELEMENTY_ZAMOWIENIA
SELECT * from  ZAGLOWE --
SELECT * from  MOTOROWE --

INSERT INTO FABRYKI 
VALUES  ('FAB1','Gdansk'),
		('FAB2','Gdansk'),
		('FAB3','Gdansk'),
		('FAB1','Gdynia'),
		('FAB2','Gdynia'),
		('FAB3','Gdynia'),
		('FAB1','Sopot'),
		('FAB2','Sopot'),
		('FAB3','Sopot'),
		('FAB1','Hel');

INSERT INTO WYPOSAZENIE
VALUES ('STANDARD','PLASTIK','PLASTIK',1,1,0),
	   ('ECO','DREWNO','DREWNO',1,1,1000),
	   ('TRAVEL','PLASTIK','DREWNO',2,1,2000),
	   ('FAMILY','PLASTIK','SKÓRA',2,2,3000),
	   ('MODERN','WŁÓKNO WĘGLOWE','DREWNO',2,2,4000),
	   ('RICH','SKÓRA','SKÓRA',3,3,5000),
	   ('TRADITIONAL','SKÓRA','SKÓRA',2,1,2500),
	   ('VISIT','SKÓRA','DREWNO',3,2,3500),
	   ('CLEAN','SKÓRA','PLASTIK',1,2,2000),
	   ('OLDSCHOOL','DREWNO','DREWNO',2,2,4500);


INSERT INTO MODELE_JACHTOW
VALUES ('ŻAGLOWE','OPEL','HUDSON',11.50,8,60000);
INSERT INTO ZAGLOWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),default,default,1);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),60000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='FAMILY'),IDENT_CURRENT('MODELE_JACHTOW'),3000+60000);

INSERT INTO MODELE_JACHTOW
VALUES('ŻAGLOWE','OPEL','CORSA',8.20,4,90000);
INSERT INTO ZAGLOWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),default,1,2);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),90000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='FAMILY'),IDENT_CURRENT('MODELE_JACHTOW'),3000+90000);

 INSERT INTO MODELE_JACHTOW
VALUES('ŻAGLOWE','OPEL','ZAFIRA',20.50,25,120000);
INSERT INTO ZAGLOWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),default,default,default);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),120000),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='RICH'),IDENT_CURRENT('MODELE_JACHTOW'),3000+120000);

INSERT INTO MODELE_JACHTOW
VALUES('ŻAGLOWE','OPEL','MONDEO',20.10,14,30000);
INSERT INTO ZAGLOWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),'Miecz',default,3);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),30000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='RICH'),IDENT_CURRENT('MODELE_JACHTOW'),3000+30000);

INSERT INTO MODELE_JACHTOW
VALUES('MOTOROWE','TOYOTA','AVENSIS',10.00,6,50000);
INSERT INTO MOTOROWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),'Benzyna',1)
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),50000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='MODERN'),IDENT_CURRENT('MODELE_JACHTOW'),3000+50000);

INSERT INTO MODELE_JACHTOW
VALUES('MOTOROWE','TOYOTA','COROLLA',12.95,7,100000);
INSERT INTO MOTOROWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),default,1);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),100000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='OLDSCHOOL'),IDENT_CURRENT('MODELE_JACHTOW'),3000+100000);

INSERT INTO MODELE_JACHTOW
VALUES('MOTOROWE','TOYOTA','AURIS',16.50,12,80000);
INSERT INTO MOTOROWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),'Benzyna',2);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),80000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='TRAVEL'),IDENT_CURRENT('MODELE_JACHTOW'),3000+80000);

INSERT INTO MODELE_JACHTOW
VALUES('MOTOROWE','TOYOTA','CLIO',14.40,12,70000);
INSERT INTO MOTOROWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),default,4);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),70000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='TRAVEL'),IDENT_CURRENT('MODELE_JACHTOW'),3000+70000);

INSERT INTO MODELE_JACHTOW
VALUES('MOTOROWE','TOYOTA','GTR',13.30,10,110000);
INSERT INTO MOTOROWE
VALUES (IDENT_CURRENT( 'MODELE_JACHTOW' ),default,3);
INSERT INTO EGZEMPLARZE_Z_WYPOSAZENIEM
VALUES ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='STANDARD' ),IDENT_CURRENT('MODELE_JACHTOW'),110000 ),
       ((SELECT ID_WYPOSAZENIA FROM WYPOSAZENIE WHERE NAZWY_WYPOSAZENIA='RICH'),IDENT_CURRENT('MODELE_JACHTOW'),3000+110000);

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Akademia Jachtingu', 'Gda�sk', '1234567890' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-08-01');
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (5,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Jachting Deluxe', 'Gda�sk', '1234587890' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ) ,'2021-06-02');
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE (NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdansk')),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 1));

-- dany klient złozyl 2  osobne zamowienia, z 1 elementem zamowienia oraz z 2 elelementami zamowienia
INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Punt', 'Gdynia', '1234560890' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-09-02' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (DEFAULT,(SELECT ID_FABRYKI FROM FABRYKI WHERE (NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Gdynia')),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 1));
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2015-12-02' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (3,(SELECT ID_FABRYKI FROM FABRYKI WHERE (NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdynia')),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 6));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE (NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Sopot')),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Punt1', 'Gdynia', '1234567891' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-09-03' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (6,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 1));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (6,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Sopot'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Akademia Jachtów', 'Gda�sk', '9234567890' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2021-02-05' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB3' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Sopot'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 6));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 6));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 1));
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-02-07' );	
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (1,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB3' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 1));

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Jachtuj', 'Gdynia', '1834567890' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-06-10' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (3,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB3' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2021-05-10' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));  

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Puntus', 'Gdynia', '1235567890' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-02-12' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Sopot'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 1));

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Żagle', 'Sopot', '1234567800' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2015-12-12' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB3' AND LOKALIZACJA ='Sopot'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 6));	

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Deluxe boat', 'Hel', '1234567000' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2022-01-01' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (3,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 6));	   

INSERT INTO KLIENCI
VALUES ('FIRMA');
INSERT INTO FIRMY 
VALUES ( IDENT_CURRENT('KLIENCI'),'Boaty', 'Gdynia', '1234007890' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2021-01-03' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (3,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdansk'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 3));

INSERT INTO KLIENCI
VALUES ('PRYWATNY');
INSERT INTO PRYWATNI 
VALUES ( IDENT_CURRENT('KLIENCI'),'Jakub','Przygoński','+48-731-233-927','jprzy@gmail.com','DA123123' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2015-12-05' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 1));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 4));

INSERT INTO KLIENCI
VALUES ('PRYWATNY');
INSERT INTO PRYWATNI 
VALUES ( IDENT_CURRENT('KLIENCI'),'Paweł','Przygoński','+48-731-233-927','pprzygon@gmail.com','DO153123' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2021-12-09' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 5));
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2021-12-12' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 5));

INSERT INTO KLIENCI
VALUES ('PRYWATNY');
INSERT INTO PRYWATNI 
VALUES ( IDENT_CURRENT('KLIENCI'),'Jan','Durkalec','+48-731-233-927','jdurka@gmail.com','DE123103' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-12-15' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (2,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB3' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 3));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB3' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 3));

INSERT INTO KLIENCI
VALUES ('PRYWATNY');
INSERT INTO PRYWATNI 
VALUES ( IDENT_CURRENT('KLIENCI'),'Marek','Przybył','+48-731-233-927','mprzybyl@gmail.com','AD122123' );
INSERT INTO ZAMOWIENIA 
VALUES ( IDENT_CURRENT( 'KLIENCI' ),'2020-12-20' );
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 2));
INSERT INTO ELEMENTY_ZAMOWIENIA
VALUES (default,(SELECT ID_FABRYKI FROM FABRYKI WHERE NAZWA_FABRYKI = 'FAB1' AND LOKALIZACJA ='Gdynia'),IDENT_CURRENT('ZAMOWIENIA'),(SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM FROM EGZEMPLARZE_Z_WYPOSAZENIEM WHERE ID_EGZEMPLARZA_Z_WYPOSAZENIEM = 2));

 
