USE STOCZNIA7

SELECT * FROM EGZEMPLARZE_Z_WYPOSAZENIEM
SELECT * FROM FABRYKI

UPDATE FABRYKI SET NAZWA_FABRYKI = 'FAB4' WHERE NAZWA_FABRYKI = 'FAB3'

SELECT * FROM EGZEMPLARZE_Z_WYPOSAZENIEM
SELECT * FROM FABRYKI

DROP TABLE EGZEMPLARZE_Z_WYPOSAZENIEM
DROP TABLE FABRYKI 

SELECT * FROM EGZEMPLARZE_Z_WYPOSAZENIEM
SELECT * FROM FABRYKI

DELETE FROM FABRYKI  WHERE NAZWA_FABRYKI = 'FAB2' AND LOKALIZACJA='Gdynia'

SELECT * FROM EGZEMPLARZE_Z_WYPOSAZENIEM
SELECT * FROM FABRYKI

CREATE VIEW EGZ_POWYZEJ_50000 AS
SELECT MARKA, MODEL 
FROM MODELE_JACHTOW 
WHERE CENA_EGZEMPLARZA>=50000

SELECT * FROM EGZ_POWYZEJ_50000

--1. PYTANIE O KONKRETNE PARAMETRY: JEDNOSTKA MOTOROWA,MINIMUM 2 TOALETY, 
--									MMINUMUM 3 PRYSZNICE, 
	--								CENA WYPOSAZENIA <= 30000, 
		--							CENA EGZEMPLARZA <=100000
-- przydatnosc dla konkretnego zamowienia z danymi parametrami do spelniania 
SELECT MODELE_JACHTOW.MARKA,MODELE_JACHTOW.MODEL,WYPOSAZENIE.ILOSC_TOALET,WYPOSAZENIE.ILOSC_PRYSZNICY,
       WYPOSAZENIE.CENA_WYPOSAZENIA,MODELE_JACHTOW.CENA_EGZEMPLARZA
FROM WYPOSAZENIE,MODELE_JACHTOW
WHERE WYPOSAZENIE.ILOSC_TOALET>=2 AND 
	  WYPOSAZENIE.ILOSC_PRYSZNICY>=3 AND 
	  WYPOSAZENIE.CENA_WYPOSAZENIA<=30000 AND
	  MODELE_JACHTOW.CENA_EGZEMPLARZA<=100000 AND
	  MODELE_JACHTOW.RODZAJ_£ODZI='MOTOROWE'


--2. EMAIL KLIENTA KTORY ZLOZYL NAJWIECEJ ZAMOWIEN MIEDZY 2019-2022
-- przydatnosc mozliwosc zaoferowania specjalnej nagrody dla najbrdziej aktywnego klienta, wyszukania emaila do kontaktu
SELECT TOP 1 PRYWATNI.EMAIL,COUNT(ZAMOWIENIA.ID_ZAMOWIENIA) AS LICZBA_ZAMOWIEN
FROM ZAMOWIENIA
INNER JOIN PRYWATNI ON ZAMOWIENIA.ID_KLIENTA=PRYWATNI.ID_PRYWATNI
WHERE ZAMOWIENIA.DATA_ZAMOWIENIA BETWEEN '2019-01-17' AND '2022-01-17' 
GROUP BY PRYWATNI.EMAIL
ORDER BY LICZBA_ZAMOWIEN DESC 

--3. SPORZADZ ZESTAWIENIE ILOSCI SPRZEDANYCH MODELI Z DOWOLNYM WYPOSA¯ENIEM
-- przydatnosc mozliwosc zaobserwowania najlepiej sprzedajacych sie modeli w celu np zwiekszenia stawek najbrdziej popularnych lub obnizenia tych najmniej
CREATE VIEW DOSTEPNE_MODELE AS 
SELECT CONCAT_WS(' ',MODELE_JACHTOW.MARKA,MODELE_JACHTOW.MODEL) AS NAZWA_MODELU, MODELE_JACHTOW.ID_MODELU_JACHTU
FROM MODELE_JACHTOW

CREATE VIEW SPRZEDANE_EGZEMPLARZE AS
SELECT ID_EGZEMPLARZA_Z_WYPOSAZENIEM,SUM(ILOSC) AS ILOSC_SPRZEDANYCH_EGZ
FROM ELEMENTY_ZAMOWIENIA
GROUP BY ID_EGZEMPLARZA_Z_WYPOSAZENIEM

SELECT DOSTEPNE_MODELE.NAZWA_MODELU, SUM(ILOSC_SPRZEDANYCH_EGZ) AS LICZBA_SPRZEDANYCH_MODELI
FROM DOSTEPNE_MODELE,SPRZEDANE_EGZEMPLARZE
INNER JOIN EGZEMPLARZE_Z_WYPOSAZENIEM ON EGZEMPLARZE_Z_WYPOSAZENIEM.ID_EGZEMPLARZA_Z_WYPOSAZENIEM=SPRZEDANE_EGZEMPLARZE.ID_EGZEMPLARZA_Z_WYPOSAZENIEM
WHERE DOSTEPNE_MODELE.ID_MODELU_JACHTU=EGZEMPLARZE_Z_WYPOSAZENIEM.ID_MODELU_JACHTU
GROUP BY DOSTEPNE_MODELE.NAZWA_MODELU

--4. POROWNANIE LICZBY ZAMOWIEN W POSZCZEGOLNYCH MIESIACACH W 2020 I 2021 ROKU, SPADEK JESLI MINUS
-- przydatnosc sprawdzenie rezultatow firmy na przestrzeni roku
CREATE VIEW ZAM1 AS
SELECT MONTH(DATA_ZAMOWIENIA) AS NR_MIESIACA_2020,COUNT(ZAMOWIENIA.ID_ZAMOWIENIA) AS LICZBA_ZAMOWIEN_2020
FROM ZAMOWIENIA
WHERE DATA_ZAMOWIENIA BETWEEN '2020-01-01' AND '2020-12-31' 
GROUP BY MONTH(DATA_ZAMOWIENIA)
CREATE VIEW ZAM2 AS
SELECT MONTH(DATA_ZAMOWIENIA) AS NR_MIESIACA_2021,COUNT(ZAMOWIENIA.ID_ZAMOWIENIA) AS LICZBA_ZAMOWIEN_2021
FROM ZAMOWIENIA
WHERE DATA_ZAMOWIENIA BETWEEN '2021-01-01' AND '2021-12-31' 
GROUP BY MONTH(DATA_ZAMOWIENIA)

SELECT COALESCE(ZAM2.NR_MIESIACA_2021,ZAM1.NR_MIESIACA_2020) AS MIESIAC,
(ISNULL(ZAM2.LICZBA_ZAMOWIEN_2021,0)-ISNULL(ZAM1.LICZBA_ZAMOWIEN_2020,0)) AS ROZNICA
FROM ZAM1
FULL JOIN ZAM2 ON ZAM1.NR_MIESIACA_2020=ZAM2.NR_MIESIACA_2021 


--5. POGRUPUJ ROSN¥CO WYPOSAZENIE ZE WZGLÊDU NA PRZEDZIAL CENOWY
-- przydatnosc klient podaje standard jakiego oczekuje, a stocznia pokazuje mu wyposazenia w tym stndardzie
SELECT NAZWY_WYPOSAZENIA, 
CASE 
	WHEN CENA_WYPOSAZENIA<=2000 THEN 'STANDARD NISKI'
	WHEN CENA_WYPOSAZENIA>2000 AND CENA_WYPOSAZENIA<4000 THEN 'STANDARD ŒREDNI'
	ELSE 'STANDARD WYSOKI'
	END AS RODZAJ_STANDARDU
FROM WYPOSAZENIE
ORDER BY RODZAJ_STANDARDU

--6. ZNAJDZ FIRMY, KTÓRE S¥ STALYMI KLIENTAMI STOCZNI (MIN 2 ZLOZONE ZAMOWIENIA )
--przydatnosc nagrodzenie stalych klientow
CREATE VIEW STALI_KLIENCI_FIRMOWI AS
SELECT FIRMY.NAZWA_FIRMY
FROM FIRMY 
INNER JOIN ZAMOWIENIA ON FIRMY.ID_FIRMY=ZAMOWIENIA.ID_KLIENTA
WHERE ID_FIRMY IN (SELECT ID_KLIENTA
					 FROM ZAMOWIENIA
					 GROUP BY ID_KLIENTA
					 HAVING COUNT(*)>=2)
					 GROUP BY FIRMY.NAZWA_FIRMY

select * from STALI_KLIENCI_FIRMOWI

-- DODATKOWE: ZESTAWIENIE WSZYTSKICH MODELI WRAZ Z WYPOSAZENIEM
-- przydatnosc pokaz mozliwych konfiguracji dla klienta
CREATE VIEW NAZWA_EGZEMPLARZY_Z_WYPOSAZENIEM AS
SELECT CONCAT_WS(' ',MODELE_JACHTOW.MARKA,MODELE_JACHTOW.MODEL,WYPOSAZENIE.NAZWY_WYPOSAZENIA) AS MOD_WYP
FROM WYPOSAZENIE, MODELE_JACHTOW
SELECT * FROM NAZWA_EGZEMPLARZY_Z_WYPOSAZENIEM

-- 7. SPORZADZ ZESTAWIENIE FABRYK W ZALEZNOSCI OD ILOSCI WYPRODUKOWANYCH JACHTOW 
--przydatnosc FABRYKE, KTORA NIE WYPRODUKOWALA ZADNEGO JACHTU MOZNA USUNAC Z BAZY
SELECT FABRYKI.NAZWA_FABRYKI,FABRYKI.LOKALIZACJA,ISNULL(SUM(ILOSC),0) AS ILOSC_W_FABRYCE
FROM ELEMENTY_ZAMOWIENIA
RIGHT JOIN FABRYKI ON FABRYKI.ID_FABRYKI=ELEMENTY_ZAMOWIENIA.ID_FABRYKI
GROUP BY FABRYKI.NAZWA_FABRYKI,FABRYKI.LOKALIZACJA
ORDER BY ILOSC_W_FABRYCE





DROP TABLE EGZEMPLARZE_Z_WYPOSAZENIEM
DROP TABLE FABRYKI 