CREATE DATABASE STOCZNIA7
USE STOCZNIA7
CREATE TABLE KLIENCI( 
	 ID_KLIENTA INT IDENTITY(1,1) PRIMARY KEY,
	 RODZAJ_KLIENTA VARCHAR(8) CHECK(RODZAJ_KLIENTA IN('PRYWATNY','FIRMA')) NOT NULL);
	
CREATE TABLE PRYWATNI( 
	 ID_PRYWATNI INT REFERENCES KLIENCI(ID_KLIENTA) PRIMARY KEY, 
	 IMIE VARCHAR(57) NOT NULL, 
	 NAZWISKO VARCHAR(200) NOT NULL,
	 NR_TELEFONU VARCHAR(15) CHECK (NR_TELEFONU LIKE '+[0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9]'),
	 EMAIL VARCHAR(255),
	 NR_DOKUMENTU VARCHAR(8) NOT NULL CHECK (NR_DOKUMENTU LIKE '[A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]' OR NR_DOKUMENTU LIKE '[A-Z][A-Z][A-Z][0-9][0-9][0-9][0-9][0-9][0-9]')
	 UNIQUE(NR_DOKUMENTU)); 

CREATE TABLE FIRMY( 
	ID_FIRMY INT REFERENCES KLIENCI(ID_KLIENTA) PRIMARY KEY, 
	NAZWA_FIRMY VARCHAR(30),
	SIEDZIBA VARCHAR(30), -- nazwa miasta
	NIP VARCHAR(10) NOT NULL CHECK (NIP LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')
	UNIQUE(NIP));
	
	
CREATE TABLE ZAMOWIENIA( 
	 ID_ZAMOWIENIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	 ID_KLIENTA  INT FOREIGN KEY REFERENCES KLIENCI(ID_KLIENTA) NOT NULL, 
	 DATA_ZAMOWIENIA DATE NOT NULL); 

CREATE TABLE FABRYKI( 
	 ID_FABRYKI INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	 NAZWA_FABRYKI VARCHAR(40) NOT NULL, 
	 LOKALIZACJA VARCHAR(30) NOT NULL, -- NAZWA MIASTA
	 UNIQUE(NAZWA_FABRYKI,LOKALIZACJA));

CREATE TABLE WYPOSAZENIE( 
     ID_WYPOSAZENIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	 NAZWY_WYPOSAZENIA VARCHAR(30) NOT NULL, 
	 RODZAJ_PODSUFITKI VARCHAR(20) NOT NULL, 
	 MATERIAL_NA_SIEDZENIACH VARCHAR(20) NOT NULL,
	 ILOSC_TOALET INT CHECK (ILOSC_TOALET >=1 AND ILOSC_TOALET <=3) NOT NULL,
	 ILOSC_PRYSZNICY INT CHECK (ILOSC_PRYSZNICY >=1 AND ILOSC_PRYSZNICY <=3) NOT NULL,
	 CENA_WYPOSAZENIA INT CHECK (CENA_WYPOSAZENIA>=0 AND CENA_WYPOSAZENIA <=10000000) NOT NULL,
	 UNIQUE(NAZWY_WYPOSAZENIA));

CREATE TABLE MODELE_JACHTOW( 
	 ID_MODELU_JACHTU INT IDENTITY(1,1) PRIMARY KEY,
	 RODZAJ_£ODZI VARCHAR(8) CHECK ( RODZAJ_£ODZI IN ('MOTOROWE','¯AGLOWE')),
	 MARKA VARCHAR(40) NOT NULL, 
	 MODEL VARCHAR(40) NOT NULL,
	 DLUGOSC DECIMAL(4,2) CHECK (DLUGOSC >=5 AND DLUGOSC <=25) NOT NULL,
	 ILOSC_KOJI INT CHECK (ILOSC_KOJI >=4 AND ILOSC_KOJI <=30) NOT NULL,
	 CENA_EGZEMPLARZA INT CHECK (CENA_EGZEMPLARZA >=5000 AND CENA_EGZEMPLARZA <=45000000) NOT NULL,
	 UNIQUE(MARKA,MODEL));

CREATE TABLE EGZEMPLARZE_Z_WYPOSAZENIEM(  
	 ID_EGZEMPLARZA_Z_WYPOSAZENIEM INT IDENTITY(1,1) PRIMARY KEY,
	 ID_WYPOSAZENIA INT FOREIGN KEY REFERENCES WYPOSAZENIE(ID_WYPOSAZENIA) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL, 
	 ID_MODELU_JACHTU INT FOREIGN KEY REFERENCES MODELE_JACHTOW(ID_MODELU_JACHTU) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	 CENA_EGZEMPLARZA_WYPOSAZENIEM INT CHECK (CENA_EGZEMPLARZA_WYPOSAZENIEM >= 5000 AND CENA_EGZEMPLARZA_WYPOSAZENIEM <100000000) NOT NULL) ;

CREATE TABLE ELEMENTY_ZAMOWIENIA( 
	 ID_ELEMENTY_ZAMOWIENIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL, 
	 ILOSC INT DEFAULT 1 NOT NULL,
	 ID_FABRYKI INT FOREIGN KEY REFERENCES FABRYKI(ID_FABRYKI) ON DELETE CASCADE ON UPDATE CASCADE NOT NULL,
	 ID_ZAMOWIENIA INT FOREIGN KEY REFERENCES ZAMOWIENIA(ID_ZAMOWIENIA) NOT NULL,
	 ID_EGZEMPLARZA_Z_WYPOSAZENIEM INT FOREIGN KEY REFERENCES EGZEMPLARZE_Z_WYPOSAZENIEM(ID_EGZEMPLARZA_Z_WYPOSAZENIEM));
CREATE TABLE ZAGLOWE( 
	 ID_ZAGLOWKI INT REFERENCES MODELE_JACHTOW(ID_MODELU_JACHTU) PRIMARY KEY, 
	 PRZYSTOSOWANIE VARCHAR(5) CHECK (PRZYSTOSOWANIE IN('Kil','Miecz')) DEFAULT('Kil') NOT NULL, 
	 ILOSC_MASZTOW INT CHECK (ILOSC_MASZTOW=1 OR ILOSC_MASZTOW=2) DEFAULT(1) NOT NULL,
	 ILOSC_KADLUBOW INT CHECK (ILOSC_KADLUBOW>=1 AND ILOSC_KADLUBOW<=3) DEFAULT(1) NOT NULL );

CREATE TABLE MOTOROWE( 
	 ID_MOTOROWKI INT REFERENCES MODELE_JACHTOW(ID_MODELU_JACHTU) PRIMARY KEY, 
	 RODZAJ_SILNIKA VARCHAR(7) CHECK (RODZAJ_SILNIKA IN('Diesel','Benzyna')) DEFAULT('Diesel') NOT NULL, 
	 ILOSC_SILNIKOW INT CHECK (ILOSC_SILNIKOW >=1 AND ILOSC_SILNIKOW <=4) DEFAULT(2) NOT NULL);

DROP TABLE KLIENCI
DROP TABLE PRYWATNI
DROP TABLE FIRMY
DROP TABLE ZAMOWIENIA
DROP TABLE FABRYKI
DROP TABLE WYPOSAZENIE
DROP TABLE EGZEMPLARZE_Z_WYPOSAZENIEM
DROP TABLE ELEMENTY_ZAMOWIENIA
DROP TABLE ZAGLOWE 
DROP TABLE MOTOROWE 

USE STOCZNIA7
